app:
  version: <%= appVersion %>
project:
  artifactId: <%= appName %>
  name: <%= appName %>
  description: <%= appDescription %>

info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
  spring:
    profiles: ${spring.profiles.active:default}
  app:
    name: ${vcap.application.name:sgl}:${vcap.application.instance_index:*}
    start: ${vcap.application.start:N/A}

spring:
  main:
    sources: <%= packageName %>.Application
  thymeleaf:
    mode: LEGACYHTML5
  jpa:
    show_sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      naming_strategy: org.hibernate.cfg.EJB3NamingStrategy
      ddl_auto: none

server:
  tomcat:
    # Write access log to target/logs/access_log.YYYY-MM-DD.log
    # See http://tomcat.apache.org/tomcat-7.0-doc/api/org/apache/catalina/valves/AccessLogValve.html
    accessLogEnabled: true
    accessLogPattern: '%h %l %u %t "%r" %s %b %{Host}i %{Location}o'
    baseDir: ''
    backgroundProcessorDelay: 1
  port: 8080

logging:
  file: logs/application_log
  level:
    ROOT: WARN
    org.apache.http: WARN
multipart:
  max-file-size: 100Mb
  max-request-size: 101Mb
---

spring:
  profiles: staging,production
security:
  require_ssl: true
server:
  # when deployed to CloudFoundry, tomcat is behind a CDN proxy
  tomcat:
    remote_ip_header: x-forwarded-for
    protocol_header: x-forwarded-proto

---

spring:
  profiles: default
  thymeleaf:
    cache: false
cache:
  timetolive: 0
---

spring:
  profiles: staging

---

spring:
  profiles: production
